version: '2.0'
services:

  #PHP Service
  app:
    build:
      args:
        user: root
        uid: 0
      # context: ./
      context: .
      dockerfile: ./docker/Dockerfile
    image: lifetime-app
    container_name: lifetime-app
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /var/www/
    volumes:
      - ./:/var/www
      - ./docker/php/laravel.ini:/usr/local/etc/php/conf.d/laravel.ini
    networks:
     - app-network

  #Nginx Service
  webserver:
    image: nginx:alpine
    container_name: lifetime-webserver
    restart: unless-stopped
    tty: true
    ports:
     - "8896:80" #localPort:dockerPort
     - "8897:443" #localPort:dockerPort
    volumes:
      - ./:/var/www
      - ./docker/nginx/conf.d:/etc/nginx/conf.d/
    networks:
      - app-network


  #MySQL Service
  db:
    image: mysql:5.7.32
    container_name: lifetime-db
    restart: unless-stopped
    tty: true
    ports:
      - "33061:3306" #localPort:dockerPort
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks:
      - app-network
    volumes:
      - ./docker/mysql/data:/var/lib/mysql
      - ./docker/mysql/my.cnf:/etc/mysql/my.cnf

#Docker Networks
networks:
  app-network:
    driver: bridge
#Volumes
# volumes:
#   ./docker/mysql/data:
#     driver: local
